server:
  port: 8097 # Bu port Euroka server portu

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false  # kendisi eureka oldugu için tekrardan Euroka'ya kayıt yapmıyoruz
    fetchRegistry: false #  Eureka sunucusunda kayıtlı olan di?er servisleri bilgilerini yerel olarak saklayacak
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
